branch-defaults:
  default:
    environment: 1650-assn-3-env
  master:
    environment: 1650-assn-3-env
    group_suffix: null
global:
  application_name: 1650-assn-3-env
  branch: null
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
